name: 'Build and push Docker image'
description: 'Build and push a single Docker image to Github Container Registry, ghcr.io.'

inputs:
  token:
    description: 'GitHub Token {{ secrets.GITHUB_TOKEN }} with the privilege set to write packages.'
    required: true
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Dockerfile location'
    required: false
    default: 'Dockerfile'
  build-args:
    description: 'List of build-time variables for the Dockerfile'
    required: false
  provenance:
    description: 'Add provenance attestations to include facts about the build process to the built images'
    required: false
    default: false
  platforms:
    description: 'List of target platforms for build'
    required: false
  pull-requests:
    description: 'If pull requests should be pushed to the registry or not.'
    required: false
    default: false
  image-name:
    description: 'Docker image name in the format <org>/<repo>. Default is {{ github.repository }}'
    required: false
    default: ${{ github.repository }}
  cache-from:
    description: 'External cache sources for buildx'
    required: false
    default: ''
  cache-to:
    description: 'Cache export destinations for buildx'
    required: false
    default: 'type=inline'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Lowercase the tags
      id: tags
      shell: bash
      run: |
        echo 'tags<<EOF' >> $GITHUB_OUTPUT
        echo '${{ steps.meta.outputs.tags }}' | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ github.event_name != 'pull_request' || inputs.pull-requests }}
        provenance: ${{ inputs.provenance }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.tags.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          ${{ inputs.cache-from }}
        cache-to: |
          ${{ inputs.cache-to }}
        build-args: |
          ${{ inputs.build-args }}
